### ISSUE TITLE
I2CP Options, Signature Configuration

### ISSUE THREAD

**Issue by eyedeekay** [i2p/i2p-rs#7]
To improve the flexibility of this library, we should find a way to allow the user to configure their signature type, and allow the user to pass I2CP and tunnel options. @bonedaddy did an example of how to do this https://github.com/bonedaddy/i2p-rs/commit/8de0ba397a667333bc0d8ae63cb5ef5431b98fad but I haven't reviewed it yet.

**Comment by bonedaddy** [comment]
There's probably a few different ways this could be accomplished, so I put together another quick example of a slightly different method of representing some of the configuration options in the commit you linked to over [in this commit](https://github.com/bonedaddy/i2p-rs/commit/96550499fe88c625fcf1ce0f9be817444bdd0651).
