### ISSUE TITLE
Tokio Usage?

### ISSUE THREAD

**Issue by eyedeekay** [i2p/i2p-rs#8]
I'm not enough of a rustacean to be completely convinced, but Tokio seems to be a widely used asynchronous I/O framework for rust which, according to the examples: https://github.com/tokio-rs/tokio might be very useful for plumbing connections between applications and I2P. Another @bonedaddy contribution, https://github.com/bonedaddy/i2p-rs/commit/9cfc2607fbf7e40d0495d4aff5393efa4a39a02c we need to give some thought to how we expose this functionality if we do it.

**Comment by bonedaddy** [comment]
What i've seen crates do is gate functionality like this behind feature flags as its not an std function. So there could be  a feature named `tokio-stream` or maybe just `tokio` which is not included in the default features, but when enabled activates this sort of functionality

**Comment by eyedeekay** [comment]
Bear with me, I had to give myself a little crash course in cargo to make sure I was seeing these things correctly. So if I'm putting the information together correctly, the major reason we need to put this behind a feature flag is because we don't want to introduce a dependency on tokio to projects that aren't using it. Makes sense to me, but my question is that if all it requires is that we set the stream up to be non-blocking then A) Can that be achieved from a library/crate that uses this one, i.e. `i2p-rs-tokio`? The question is pretty much academic I guess, for a ~10 line diff for a feature behind an it's not making the library more difficult to understand or use, and I'm pretty sure it's easier to put here than in a new library, but I'm curious about pros and cons. Going to think about it some more, I'd like to hear your thoughts. Take your time.

**Comment by bonedaddy** [comment]
No worries, my experience with cargo is fairly limited as well.

> So if I'm putting the information together correctly, the major reason we need to put this behind a feature flag is because we don't want to introduce a dependency on tokio to projects that aren't using it. 

Yup.

> but my question is that if all it requires is that we set the stream up to be non-blocking then: Can that be achieved from a library/crate that uses this one, i.e. i2p-rs-tokio? The question is pretty much academic I guess, for a ~10 line diff for a feature behind an it's not making the library more difficult to understand or use, and I'm pretty sure it's easier to put here than in a new library, but I'm curious about pros and cons. Going to think about it some more, I'd like to hear your thoughts. Take your time.

So this sort of depends. Right now the relevant fields of [`I2pStream`](https://github.com/bonedaddy/i2p-rs/blob/9cfc2607fbf7e40d0495d4aff5393efa4a39a02c/src/net/streaming.rs#L32), as well as [session / sam connection](https://github.com/bonedaddy/i2p-rs/blob/9cfc2607fbf7e40d0495d4aff5393efa4a39a02c/src/sam.rs#L59) are private so the only way this can be achieved is the addition of the extra functions I added.

I agree with your point that it doesnt make very much sense to add the extra code and the `tokio` dependency to `i2p-rs`. The simplest solution i can think of is to mark the fields as `pub` or i guess add some sort of getter function. If the fields were public or there was a getter function a different crate could be used like you suggested with `i2p-rs-tokio`.

Not sure what the most idiomatic rust approach is here, this is getting into the area of rust im very new in :thinking:

**Comment by eyedeekay** [comment]
Well I'm not sure yet, but I'm leaning toward making the fields public. My reasoning is predicated on the notion that extending with another library, i.e. `i2p-rs-tokio` is a good idea compared to the feature flag. If it's a good idea for tokio, then it's probably true for other libraries, and if it's a required for tokio, then it's probably important for something else. So IMO if we can change the *scope* or make the getter/setter available per the setting of a feature flag, we've arrived at the best solution because it avoids adding things to this library that aren't strictly required, and makes it possible for other developers to optionally access internals should they require them.

**Comment by bonedaddy** [comment]
Makes sense and agreed. I can take a stab at implementing this and send a PR once it's ready for a review
